In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt

import scanpy as sc
import anndata

## Mycellia Data

In [3]:
basedir = "/home/data/kaggle_data/myllia/"

In [ ]:
df1 = pd.read_csv(basedir+"training_data_means.csv")
print(df1.shape)
print(df1.tail())
# df1.loc[df1["pert_symbol"] == "WAC", "WAC"]

(81, 5128)
      pert_symbol      A1BG      A1CF     AADAC      AAK1     AARS1      AASS  \
76         TGFBR2  0.537884  0.015554  0.106994  0.455972  0.723697  0.005621
77          USP22  0.443085  0.044874  0.123302  0.288553  0.675256  0.000000
78          VEGFA  0.498489  0.009164  0.096523  0.420647  0.753090  0.003990
79            WAC  0.481894  0.023404  0.085533  0.476920  0.801459  0.000000
80  non-targeting  0.474062  0.025797  0.093244  0.443709  0.737890  0.002591

       ABCA1    ABCA12     ABCA5  ...       ZP3      ZPBP    ZRANB3   ZSCAN18  \
76  0.162179  0.024584  0.107136  ...  0.311330  0.002471  0.516634  0.011630
77  0.087892  0.041430  0.095096  ...  0.362282  0.000000  0.468844  0.010474
78  0.135827  0.017036  0.085875  ...  0.298464  0.000000  0.535847  0.005435
79  0.152639  0.027180  0.129683  ...  0.253768  0.002552  0.555070  0.010930
80  0.137953  0.018650  0.099708  ...  0.283082  0.000991  0.526363  0.009778

     ZSCAN31    ZSWIM5    ZSWIM6    ZSWIM7     ZWINT       ZYX
76  0.063854  0.077293  0.936977  0.731447  0.690297  0.639862
77  0.027139  0.076007  1.033585  0.765131  0.633493  0.659664
78  0.083804  0.095018  0.821152  0.698710  0.699610  0.634970
79  0.043947  0.125091  0.846153  0.693998  0.703783  0.726951
80  0.046621  0.078303  0.860658  0.719807  0.707353  0.681142

[5 rows x 5128 columns]

In [6]:
df2 = pd.read_csv(basedir+"sample_submission.csv")
print(df2.shape)
print(df2.head())

(120, 5128)
  pert_id      A1BG      A1CF    AADAC      AAK1     AARS1      AASS  \
0  pert_1  0.011603  0.000986 -0.00299 -0.000908 -0.006582 -0.000028
1  pert_2  0.011603  0.000986 -0.00299 -0.000908 -0.006582 -0.000028
2  pert_3  0.011603  0.000986 -0.00299 -0.000908 -0.006582 -0.000028
3  pert_4  0.011603  0.000986 -0.00299 -0.000908 -0.006582 -0.000028
4  pert_5  0.011603  0.000986 -0.00299 -0.000908 -0.006582 -0.000028

      ABCA1    ABCA12     ABCA5  ...       ZP3      ZPBP    ZRANB3   ZSCAN18  \
0 -0.002154 -0.000425  0.010644  ...  0.027073 -0.000251  0.002195  0.002279
1 -0.002154 -0.000425  0.010644  ...  0.027073 -0.000251  0.002195  0.002279
2 -0.002154 -0.000425  0.010644  ...  0.027073 -0.000251  0.002195  0.002279
3 -0.002154 -0.000425  0.010644  ...  0.027073 -0.000251  0.002195  0.002279
4 -0.002154 -0.000425  0.010644  ...  0.027073 -0.000251  0.002195  0.002279

    ZSCAN31    ZSWIM5    ZSWIM6    ZSWIM7     ZWINT       ZYX
0  0.007285  0.012135 -0.018211 -0.023067 -0.015754 -0.006962
1  0.007285  0.012135 -0.018211 -0.023067 -0.015754 -0.006962
2  0.007285  0.012135 -0.018211 -0.023067 -0.015754 -0.006962
3  0.007285  0.012135 -0.018211 -0.023067 -0.015754 -0.006962
4  0.007285  0.012135 -0.018211 -0.023067 -0.015754 -0.006962

[5 rows x 5128 columns]

In [30]:
df3 = pd.read_csv(basedir+"pert_ids_val.csv")
print(df3.shape)
print(df3.head())

(60, 3)
      pert class pert_id
0  SMARCE1   val  pert_1
1     DPF2   val  pert_2
2    MRE11   val  pert_3
3   TCF7L2   val  pert_4
4   HMGXB4   val  pert_5

In [32]:
df4 = pd.read_csv(basedir+"training_data_ground_truth_table.csv")
print(df4.shape)
print(df4.head())

(80, 10256)
  pert_id      A1BG      A1CF     AADAC      AAK1     AARS1      AASS  \
0    ACLY -0.162420 -0.003694  0.007704 -0.065038 -0.022033 -0.002591
1   ALDOA  0.153383  0.018165  0.001091 -0.001647 -0.079765 -0.002591
2   APAF1 -0.006948  0.004917 -0.002335  0.026446 -0.005120  0.000229
3   ARID2  0.043123 -0.007021  0.009316  0.001984 -0.050810  0.007644
4    BAG1 -0.065040  0.009065  0.036724  0.019140  0.081988  0.000408

      ABCA1    ABCA12     ABCA5  ...    w_ZPBP  w_ZRANB3  w_ZSCAN18  \
0 -0.019053  0.012141 -0.012702  ...  0.005787  3.673932   0.241709
1  0.062238 -0.018650 -0.038159  ...  0.010308  2.072907   1.071005
2 -0.019583  0.007200  0.037674  ...  0.039448  0.039448   0.039448
3 -0.013434 -0.002272  0.023748  ...  0.015171  0.103470   0.015171
4 -0.012373 -0.015974  0.031339  ...  0.024883  2.457045   0.024883

   w_ZSCAN31  w_ZSWIM5  w_ZSWIM6  w_ZSWIM7   w_ZWINT     w_ZYX  baseline_wmae
0   0.005787  0.023946  0.450036  1.130375  0.005787  2.279422       0.171164
1   0.868602  0.403595  0.015927  0.056200  2.120163  1.548899       0.159152
2   0.039448  0.039448  0.039448  0.039448  0.039448  0.039448       0.107923
3   0.015171  0.015171  7.626104  7.328505  2.750918  1.421091       0.095729
4   0.024883  4.941543  0.411202  0.024883  0.967044  0.267855       0.112668

[5 rows x 10256 columns]

In [42]:
adata = sc.read_h5ad(basedir+"training_cells.h5ad")
print(adata)
# print(adata.X)
print(adata.obs)
print(adata.var)
print(adata.obs["sgrna_symbol"].nunique())

AnnData object with n_obs × n_vars = 17882 × 19226
    obs: 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'sgrna_id', 'sgrna_symbol', 'channel'
    var: 'features'
                       nCount_RNA  nFeature_RNA  percent.mt          sgrna_id  \
AAACCAAAGACGCGAA_ch_1     16395.0          4191    4.306191          INSIG1_3
AAACCAAAGCAAATGA_ch_1     12000.0          3631    3.133333            FLNA_2
AAACCAAAGCAGTCTA_ch_1     55050.0          7061    5.193460           EIF3H_2
AAACCAAAGGGCATAG_ch_1     19586.0          5010    6.494435           DZIP3_4
AAACCATTCCAATCGA_ch_1     18744.0          4697    4.604140  non-targeting_25
...                           ...           ...         ...               ...
GTTGTCCGTCCAGTGA_ch_4     21242.0          4904    4.057998          METTL3_4
GTTGTCCGTGGGTTTG_ch_4     17462.0          4674    3.928531  non-targeting_25
GTTGTCTTCCCCAACC_ch_4     10459.0          3350    6.922268           IKBKG_1
GTTGTCTTCCCTTCTC_ch_4     29779.0          5709    3.680446            EGFR_2
GTTGTGCAGCGCCACA_ch_4     29557.0          5683    0.003383            TFAM_4

                        sgrna_symbol channel
AAACCAAAGACGCGAA_ch_1         INSIG1    ch_1
AAACCAAAGCAAATGA_ch_1           FLNA    ch_1
AAACCAAAGCAGTCTA_ch_1          EIF3H    ch_1
AAACCAAAGGGCATAG_ch_1          DZIP3    ch_1
AAACCATTCCAATCGA_ch_1  non-targeting    ch_1
...                              ...     ...
GTTGTCCGTCCAGTGA_ch_4         METTL3    ch_4
GTTGTCCGTGGGTTTG_ch_4  non-targeting    ch_4
GTTGTCTTCCCCAACC_ch_4          IKBKG    ch_4
GTTGTCTTCCCTTCTC_ch_4           EGFR    ch_4
GTTGTGCAGCGCCACA_ch_4           TFAM    ch_4

[17882 rows x 6 columns]
        features
A1BG        A1BG
A1CF        A1CF
A2M          A2M
A2ML1      A2ML1
A3GALT2  A3GALT2
...          ...
ZYG11A    ZYG11A
ZYG11B    ZYG11B
ZYX          ZYX
ZZEF1      ZZEF1
ZZZ3        ZZZ3

[19226 rows x 1 columns]
81

In [ ]:
df = adata.to_df()
df.head()

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,RNF223,C1orf159,...,MT-ND2,MT-CO2,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,MT-ND4,MT-ND5,MT-ND6,MT-CYB
AAACAAGCAACCTTGTACTTTAGG-Flex_1_01,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,4.0,0.0,0.0,1.0
AAACAAGCATTGCCGCACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,2.0,2.0,3.0,3.0,0.0,3.0,0.0,0.0,1.0
AAACCAATCAATGTTCACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,4.0,6.0,0.0,1.0,...,0.0,7.0,5.0,2.0,5.0,0.0,5.0,0.0,2.0,1.0
AAACCAATCCCTCGCTACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,2.0,8.0,0.0,1.0,...,0.0,4.0,5.0,3.0,8.0,2.0,10.0,0.0,4.0,2.0
AAACCAATCTAAATCCACTTTAGG-Flex_1_01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0

## VCC Data

In [6]:
basedir = "/home/data/kaggle_data/myllia/vcc_2025/"

In [10]:
adata = sc.read_h5ad(basedir + "adata_Training.h5ad")
print(adata)
# print(adata.X)
print(adata.obs)
print(adata.var)

AnnData object with n_obs × n_vars = 221273 × 18080
    obs: 'target_gene', 'guide_id', 'batch'
    var: 'gene_id'
                                      target_gene  \
AAACAAGCAACCTTGTACTTTAGG-Flex_1_01          CHMP3
AAACAAGCATTGCCGCACTTTAGG-Flex_1_01           AKT2
AAACCAATCAATGTTCACTTTAGG-Flex_1_01          SHPRH
AAACCAATCCCTCGCTACTTTAGG-Flex_1_01         TMSB4X
AAACCAATCTAAATCCACTTTAGG-Flex_1_01          KLF10
...                                           ...
TTTGGACGTGGTGCAGATTCGGTT-Flex_3_16  non-targeting
TTTGTGAGTAGTAGCAATTCGGTT-Flex_3_16          KDM1A
TTTGTGAGTCCATCCTATTCGGTT-Flex_3_16  non-targeting
TTTGTGAGTCCTGACAATTCGGTT-Flex_3_16          BIRC2
TTTGTGAGTGGACACGATTCGGTT-Flex_3_16          EWSR1

                                                                   guide_id  \
AAACAAGCAACCTTGTACTTTAGG-Flex_1_01                CHMP3_P1P2_A|CHMP3_P1P2_B
AAACAAGCATTGCCGCACTTTAGG-Flex_1_01                  AKT2_P1P2_A|AKT2_P1P2_B
AAACCAATCAATGTTCACTTTAGG-Flex_1_01                SHPRH_P1P2_A|SHPRH_P1P2_B
AAACCAATCCCTCGCTACTTTAGG-Flex_1_01                  TMSB4X_P1_A|TMSB4X_P1_B
AAACCAATCTAAATCCACTTTAGG-Flex_1_01                    KLF10_P2_A|KLF10_P2_B
...                                                                     ...
TTTGGACGTGGTGCAGATTCGGTT-Flex_3_16  non-targeting_00035|non-targeting_03439
TTTGTGAGTAGTAGCAATTCGGTT-Flex_3_16                KDM1A_P1P2_A|KDM1A_P1P2_B
TTTGTGAGTCCATCCTATTCGGTT-Flex_3_16  non-targeting_00020|non-targeting_01323
TTTGTGAGTCCTGACAATTCGGTT-Flex_3_16                BIRC2_P1P2_A|BIRC2_P1P2_B
TTTGTGAGTGGACACGATTCGGTT-Flex_3_16                EWSR1_P1P2_A|EWSR1_P1P2_B

                                        batch
AAACAAGCAACCTTGTACTTTAGG-Flex_1_01  Flex_1_01
AAACAAGCATTGCCGCACTTTAGG-Flex_1_01  Flex_1_01
AAACCAATCAATGTTCACTTTAGG-Flex_1_01  Flex_1_01
AAACCAATCCCTCGCTACTTTAGG-Flex_1_01  Flex_1_01
AAACCAATCTAAATCCACTTTAGG-Flex_1_01  Flex_1_01
...                                       ...
TTTGGACGTGGTGCAGATTCGGTT-Flex_3_16  Flex_3_16
TTTGTGAGTAGTAGCAATTCGGTT-Flex_3_16  Flex_3_16
TTTGTGAGTCCATCCTATTCGGTT-Flex_3_16  Flex_3_16
TTTGTGAGTCCTGACAATTCGGTT-Flex_3_16  Flex_3_16
TTTGTGAGTGGACACGATTCGGTT-Flex_3_16  Flex_3_16

[221273 rows x 3 columns]
                 gene_id
SAMD11   ENSG00000187634
NOC2L    ENSG00000188976
KLHL17   ENSG00000187961
PLEKHN1  ENSG00000187583
PERM1    ENSG00000187642
...                  ...
MT-ND4L  ENSG00000212907
MT-ND4   ENSG00000198886
MT-ND5   ENSG00000198786
MT-ND6   ENSG00000198695
MT-CYB   ENSG00000198727

[18080 rows x 1 columns]

In [8]:
df = adata.to_df()
df.head()

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,RNF223,C1orf159,...,MT-ND2,MT-CO2,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,MT-ND4,MT-ND5,MT-ND6,MT-CYB
AAACAAGCAACCTTGTACTTTAGG-Flex_1_01,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,4.0,0.0,0.0,1.0
AAACAAGCATTGCCGCACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,2.0,2.0,3.0,3.0,0.0,3.0,0.0,0.0,1.0
AAACCAATCAATGTTCACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,4.0,6.0,0.0,1.0,...,0.0,7.0,5.0,2.0,5.0,0.0,5.0,0.0,2.0,1.0
AAACCAATCCCTCGCTACTTTAGG-Flex_1_01,0.0,1.0,0.0,0.0,0.0,0.0,2.0,8.0,0.0,1.0,...,0.0,4.0,5.0,3.0,8.0,2.0,10.0,0.0,4.0,2.0
AAACCAATCTAAATCCACTTTAGG-Flex_1_01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0